"""AI-assisted Pull Request and Contribution Reviewer for GitHub Activity Lab.

Supports Anthropic Claude API (Claude 3.7 Sonnet / Claude 3.5 Sonnet),
local Claude CLI execution, and zero-dependency heuristic fallback.
"""

from __future__ import annotations

import json
import os
import subprocess
import urllib.request
import urllib.error
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any

from activity_lab.coauthor_checker import validate_coauthor_string
from activity_lab.commit_linter import validate_commit_message


@dataclass
class ReviewResult:
    """Summary and findings from an AI-assisted PR or commit review."""
    title: str
    is_conventional: bool
    summary: str
    highlights: List[str] = field(default_factory=list)
    suggested_coauthors: List[str] = field(default_factory=list)
    risk_level: str = "LOW"  # LOW, MEDIUM, HIGH
    source: str = "heuristic"  # "claude-api", "claude-cli", or "heuristic"

    def to_markdown(self) -> str:
        """Render review result to GitHub-flavored markdown."""
        status_icon = "✅" if self.is_conventional else "⚠️"
        risk_badge = {
            "LOW": "🟢 Low Risk",
            "MEDIUM": "🟡 Medium Risk",
            "HIGH": "🔴 High Risk",
        }.get(self.risk_level, "⚪ Unknown")

        lines = [
            "### 🤖 GitHub Activity Lab - AI PR Review",
            f"- **Conventional Title:** {status_icon} `{self.title}`",
            f"- **Risk Assessment:** {risk_badge}",
            f"- **Review Engine:** `{self.source}`",
            "",
            "#### Summary",
            self.summary.strip(),
            "",
        ]

        if self.highlights:
            lines.append("#### Key Highlights & Changes")
            for h in self.highlights:
                lines.append(f"- {h}")
            lines.append("")

        if self.suggested_coauthors:
            lines.append("#### Suggested Co-Authors Detected")
            for ca in self.suggested_coauthors:
                valid = "✓" if validate_coauthor_string(f"Co-authored-by: {ca}") else "?"
                lines.append(f"- {valid} `{ca}`")
            lines.append("")

        lines.append("---")
        lines.append("*Generated by [GitHub Activity Lab](https://github.com/UmeshCode1/lets-connect).*")
        return "\n".join(lines)


def generate_heuristic_review(
    title: str,
    body: str = "",
    diff: str = "",
    commit_messages: Optional[List[str]] = None,
) -> ReviewResult:
    """Zero-dependency deterministic review engine used offline or without API key."""
    is_conv = validate_commit_message(title)
    commits = commit_messages or []

    # Detect co-authors in commit messages or body
    suggested_coauthors: List[str] = []
    text_corpus = f"{body}\n" + "\n".join(commits)
    for line in text_corpus.splitlines():
        line_clean = line.strip()
        if line_clean.lower().startswith("co-authored-by:"):
            author_val = line_clean.split(":", 1)[1].strip()
            if author_val and author_val not in suggested_coauthors:
                suggested_coauthors.append(author_val)

    # Calculate highlights based on diff/commits
    highlights: List[str] = []
    if commits:
        highlights.append(f"Analyzed {len(commits)} commit(s) in this pull request.")
        for msg in commits[:3]:
            first_line = msg.splitlines()[0].strip()
            highlights.append(f"Commit: `{first_line}`")
    elif diff:
        diff_lines = diff.splitlines()
        additions = sum(1 for l in diff_lines if l.startswith("+") and not l.startswith("+++"))
        deletions = sum(1 for l in diff_lines if l.startswith("-") and not l.startswith("---"))
        highlights.append(f"Diff stats: +{additions} lines added, -{deletions} lines deleted.")

    # Determine risk level
    risk = "LOW"
    lower_diff = diff.lower()
    lower_title = title.lower()
    high_risk_words = ["drop table", "credentials", "secret_key", "private_key", "password_hash", "rm -rf"]
    medium_risk_words = ["security", "auth", "token", "permission"]

    if any(k in lower_diff or k in lower_title for k in high_risk_words):
        risk = "HIGH"
    elif any(k in lower_diff or k in lower_title for k in medium_risk_words) or len(diff.splitlines()) > 500 or len(commits) > 15:
        risk = "MEDIUM"


    summary_text = (
        f"Pull request '{title}' processed cleanly. "
        + ("Commit message complies with Conventional Commits specifications." if is_conv else "Consider using a Conventional Commit prefix (e.g. feat:, fix:, docs:).")
    )
    if body:
        summary_text += f"\nDescription provided: {body.strip()[:200]}"

    return ReviewResult(
        title=title,
        is_conventional=is_conv,
        summary=summary_text,
        highlights=highlights,
        suggested_coauthors=suggested_coauthors,
        risk_level=risk,
        source="heuristic",
    )


def call_anthropic_api(
    prompt: str,
    api_key: str,
    model: str = "claude-3-7-sonnet-20250219",
) -> Optional[str]:
    """Call the Anthropic Messages API using standard library urllib."""
    url = "https://api.anthropic.com/v1/messages"
    headers = {
        "x-api-key": api_key,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
    }
    payload = {
        "model": model,
        "max_tokens": 1024,
        "messages": [
            {"role": "user", "content": prompt}
        ]
    }

    try:
        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode("utf-8"),
            headers=headers,
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=30) as response:
            if response.status == 200:
                data = json.loads(response.read().decode("utf-8"))
                contents = data.get("content", [])
                if contents and "text" in contents[0]:
                    return contents[0]["text"]
    except Exception:
        return None
    return None


def call_claude_cli(prompt: str) -> Optional[str]:
    """Invoke the local Claude ant CLI if installed and authenticated."""
    try:
        # Check if ant.exe or claude is available
        res = subprocess.run(
            ["ant", "--version"],
            capture_output=True,
            text=True,
            timeout=5,
            shell=True,
        )
        if res.returncode == 0:
            run_cmd = subprocess.run(
                ["ant", "-p", prompt],
                capture_output=True,
                text=True,
                timeout=30,
                shell=True,
            )
            if run_cmd.returncode == 0 and run_cmd.stdout.strip():
                return run_cmd.stdout.strip()
    except Exception:
        pass
    return None


def review_pull_request(
    title: str,
    body: str = "",
    diff: str = "",
    commit_messages: Optional[List[str]] = None,
    api_key: Optional[str] = None,
    use_cli: bool = False,
    model: str = "claude-3-7-sonnet-20250219",
) -> ReviewResult:
    """Review pull request using Anthropic Claude API, CLI, or heuristic fallback."""
    key = api_key or os.environ.get("ANTHROPIC_API_KEY")

    prompt = (
        f"You are a strict and helpful open-source code reviewer for GitHub Activity Lab.\n"
        f"Review this Pull Request:\n"
        f"Title: {title}\n"
        f"Body: {body}\n"
        f"Commits: {commit_messages}\n"
        f"Diff snippet (first 1000 chars): {diff[:1000]}\n\n"
        f"Provide a JSON response with keys: 'summary' (string), 'highlights' (array of strings), "
        f"'suggested_coauthors' (array of strings 'Name <email>'), 'risk_level' ('LOW', 'MEDIUM', 'HIGH')."
    )

    # 1. Try Anthropic API if key is present
    if key:
        raw_text = call_anthropic_api(prompt, api_key=key, model=model)
        if raw_text:
            try:
                # Extract JSON if enclosed in markdown blocks
                clean_json = raw_text.strip()
                if "```json" in clean_json:
                    clean_json = clean_json.split("```json", 1)[1].split("```", 1)[0].strip()
                elif "```" in clean_json:
                    clean_json = clean_json.split("```", 1)[1].split("```", 1)[0].strip()
                data = json.loads(clean_json)
                return ReviewResult(
                    title=title,
                    is_conventional=validate_commit_message(title),
                    summary=data.get("summary", "AI review completed."),
                    highlights=data.get("highlights", []),
                    suggested_coauthors=data.get("suggested_coauthors", []),
                    risk_level=data.get("risk_level", "LOW"),
                    source=f"claude-api ({model})",
                )
            except Exception:
                pass

    # 2. Try Claude CLI if enabled
    if use_cli:
        cli_out = call_claude_cli(prompt)
        if cli_out:
            try:
                clean_json = cli_out.strip()
                if "```json" in clean_json:
                    clean_json = clean_json.split("```json", 1)[1].split("```", 1)[0].strip()
                elif "```" in clean_json:
                    clean_json = clean_json.split("```", 1)[1].split("```", 1)[0].strip()
                data = json.loads(clean_json)
                return ReviewResult(
                    title=title,
                    is_conventional=validate_commit_message(title),
                    summary=data.get("summary", "AI CLI review completed."),
                    highlights=data.get("highlights", []),
                    suggested_coauthors=data.get("suggested_coauthors", []),
                    risk_level=data.get("risk_level", "LOW"),
                    source="claude-cli",
                )
            except Exception:
                pass

    # 3. Graceful heuristic fallback
    return generate_heuristic_review(title, body, diff, commit_messages)
