"""Markdown activity report generator."""
from __future__ import annotations
from typing import Dict, Any

def generate_markdown_report(metrics: Dict[str, Any]) -> str:
    """Format repository metrics into a GitHub Flavored Markdown report."""
    lines = [
        "# Repository Activity Report",
        "",
        f"**Repository:** `{metrics.get('repo', 'unknown')}`",
        f"**Generated:** `{metrics.get('date', 'N/A')}`",
        "",
        "## Key Performance Indicators",
        f"- **Total Commits:** {metrics.get('commits', 0)}",
        f"- **Merged Pull Requests:** {metrics.get('prs', 0)}",
        f"- **Active Contributors:** {metrics.get('contributors', 0)}",
        "",
        "---",
        "*Report generated by activity-lab.*"
    ]
    return "\n".join(lines)
