"""Release notes formatting module."""
from __future__ import annotations
from typing import List

def format_release_notes(tag: str, title: str, highlights: List[str]) -> str:
    """Construct markdown release notes document."""
    lines = [
        f"## {title} ({tag})",
        "",
        "### Key Highlights",
    ]
    for h in highlights:
        lines.append(f"- {h}")
    lines.extend(["", "---", "*Automated release notes generated by activity-lab.*"])
    return "\n".join(lines)
